import { useContext, useEffect, useRef, useState } from 'react';
import type { NextPage } from 'next';
import CSS from './index.module.scss';
import cName from 'classnames';
import { ThemeContext } from '@/stores/theme';

interface IProps {
  title: string;
  description: string;
  list: {
    label: string;
    info: string;
    link: string;
  };
}

const Home: NextPage<IProps> = ({ title, description, list }) => {
  const mainRef = useRef<HTMLDivElement>(null);
  const { theme } = useContext(ThemeContext);

  useEffect(() => {
    mainRef.current?.classList.remove(CSS.withAnimation);
    window.requestAnimationFrame(() => {
      mainRef.current?.classList.add(CSS.withAnimation);
    });
  }, [theme]);

  return (
    <div className={CSS.container}>
      <main className={cName([CSS.main, CSS.withAnimation])} ref={mainRef}>
        <h1 className={CSS.title}>{title}</h1>
        <p className={CSS.description}>{description}</p>
        <div className={CSS.grid}>
          {list?.map((item, index) => {
            return (
              <div
                className={CSS.card}
                key={index}
                onClick={(): void => {
                  window.open(
                    item.link,
                    'blank',
                    'noopener=yes,noreferrer=yes' //  为了跳转的安全性， 这个可以隐藏我们跳转的 window.opener与Document.referrer, 在跨站点跳转中，我们通常加这个参数来确保信息的不泄露
                  );
                }}
              >
                <h2>{item.label}&rarr;</h2>
                <p>{item.info}</p>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

Home.getInitialProps = context => {
  return {
    title: 'Hello',
    description: 'A Demo for',
    list: [
      {
        label: '文章1',
        info: 'A test for article1',
        link: 'http://localhost:3000/article/1',
      },
      {
        label: '文章2',
        info: 'A test for article2',
        link: 'http://localhost:3000/article/2',
      },
      {
        label: '文章3',
        info: 'A test for article3',
        link: 'http://localhost:3000/article/3',
      },
      {
        label: '文章4',
        info: 'A test for article4',
        link: 'http://localhost:3000/article/4',
      },
      {
        label: '文章5',
        info: 'A test for article5',
        link: 'http://localhost:3000/article/5',
      },
      {
        label: '文章6',
        info: 'A test for article2',
        link: 'http://localhost:3000/article/6',
      },
    ],
  };
};

export default Home;

// import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from '@next/font/google';
// import styles from '@/styles/Home.module.scss';

// const inter = Inter({ subsets: ['latin'] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   );
// }
